create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  role text not null default 'user' check (role in ('admin', 'user')),
  points integer not null default 0 check (points >= 0),
  created_at timestamptz not null default now()
);

create table public.gifts (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  points_cost integer not null check (points_cost > 0),
  image_url text,
  created_at timestamptz not null default now()
);

create table public.point_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount integer not null,
  reason text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.gifts enable row level security;
alter table public.point_transactions enable row level security;

create policy "Users can read their own profile" on public.profiles
  for select using (auth.uid() = id);
create policy "Users can read gifts" on public.gifts
  for select using (auth.role() = 'authenticated');
create policy "Users can read their own point history" on public.point_transactions
  for select using (auth.uid() = user_id);

-- Create the first account in Authentication, then run:
-- update public.profiles set role = 'admin' where email = 'your-admin-email@example.com';